Fix checks for new album art support

diff --git a/test/test_filesize b/test/test_filesize
--- a/test/test_filesize
+++ b/test/test_filesize
@@ -2,74 +2,58 @@
 
 . "${BASH_SOURCE%/*}/funcs.sh" "$1"
 
+check() {
+    FILE="$1"
+    MIN="$2"
+    MAX="$3"
+
+    if [ -z $MAX  ]
+    then
+        MAX=$MIN
+    fi
+
+    SIZE=$(stat -c %s "$DIRNAME/$FILE")
+    echo "File: $FILE"
+    if [ $MIN -eq $MAX ]
+    then
+        echo "Size: $SIZE (expected $MIN)"
+    else
+        echo "Size: $SIZE (expected $MIN...$MAX)"
+    fi
+
+    if [ $SIZE -ge $MIN -a $SIZE -le $MAX ]
+    then
+        echo "Pass"
+    else
+        echo "FAIL!"
+        exit 1
+    fi
+}
+
 # Ensure log contains file sizes, predicted and actual
 cat "$DIRNAME/obama.$DESTTYPE" > /dev/null
 cat "$DIRNAME/raven.$DESTTYPE" > /dev/null
 
 if [ "$DESTTYPE" == "mp4" ];
 then
-# mp4
-
-echo Checking $DIRNAME/obama.mp4
-SIZE=$(stat -c %s "$DIRNAME/obama.mp4")
-echo Size: $SIZE
-[ $SIZE -ge 99151 -a $SIZE -le 100191 ]
-echo "Pass"
-
-echo Checking $DIRNAME/raven.mp4
-SIZE=$(stat -c %s "$DIRNAME/raven.mp4")
-echo Size: $SIZE
-[ $SIZE -ge 133661 -a $SIZE -le 137281 ]
-echo "Pass"
-
+    # mp4
+    check "obama.mp4" 99151 113048
+    check "raven.mp4" 133661 137986
 elif [ "$DESTTYPE" == "mp3" ];
 then
-# mp3
-
-echo Checking $DIRNAME/obama.mp3
-SIZE=$(stat -c %s "$DIRNAME/obama.mp3")
-echo Size: $SIZE
-[ $SIZE -eq 97244 ]
-echo "Pass"
-
-echo Checking $DIRNAME/raven.mp3
-SIZE=$(stat -c %s "$DIRNAME/raven.mp3")
-echo Size: $SIZE
-[ $SIZE -eq 126456 ]
-echo "Pass"
-
+    # mp3
+    check "obama.mp3" 107101
+    check "raven.mp3" 126456
 elif [ "$DESTTYPE" == "wav" ];
 then
-# wav
-
-echo Checking $DIRNAME/obama.wav
-SIZE=$(stat -c %s "$DIRNAME/obama.wav")
-echo Size: $SIZE
-[ $SIZE -eq 1058636 ]
-echo "Pass"
-
-echo Checking $DIRNAME/raven.wav
-SIZE=$(stat -c %s "$DIRNAME/raven.wav")
-echo Size: $SIZE
-[ $SIZE -eq 3699406 ]
-echo "Pass"
-
+    # wav
+    check "obama.wav" 1058636
+    check "raven.wav" 3699406
 elif [ "$DESTTYPE" == "ogg" ];
 then
-# ogg
-
-echo Checking $DIRNAME/obama.ogg
-SIZE=$(stat -c %s "$DIRNAME/obama.ogg")
-echo Size: $SIZE
-[ $SIZE -eq 65633 ]
-echo "Pass"
-
-echo Checking $DIRNAME/raven.ogg
-SIZE=$(stat -c %s "$DIRNAME/raven.ogg")
-echo Size: $SIZE
-[ $SIZE -eq 141211 ]
-echo "Pass"
-
+    # ogg
+    check "obama.ogg" 66181
+    check "raven.ogg" 141211
 else
 echo "Internal error, unknown type $DESTTYPE. Fix script!"
 exit 99
